### ISSUE TITLE
Update counters when a peer is disconnected

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/PeerNet#15]
When a peer is disconnected, because his thread fail or have his socket shutdown we need to change the counters and infos in `active_connections` of the manager. Related to : https://github.com/massalabs/PeerNet/blob/main/src/peer.rs#L91

**Comment by litchipi** [comment]
Blocked by #16 , will handle it once merged

**Comment by litchipi** [comment]
Will be implemented by #18
